### ISSUE TITLE
Can you support for external links ? 

### ISSUE THREAD

**Issue by nntloc** [h5p/h5p-memory-game#14]
We have some images in our website, so we don't want re-upload in Memory Game. Can you support for external links ?

**Comment by icc** [comment]
Hi! Apologies, for the late response. This is a feature that makes the most sense to add through the H5P plugin. This way all image fields would get it.

Feel free to create an issue for the editor at [h5p/h5p-editor-php-library](/h5p/h5p-editor-php-library/issues).
