### ISSUE TITLE
IE11 & memory game doesn't work right

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-memory-game#24]
Hello,

in Moodle 3.3 and mod_hvp 1.3 2017052400 with Internet Explorer 11 you can turn all the pages in memory game at once. With chrome it works fine.

![memorygame](https://cloud.githubusercontent.com/assets/15193418/26676075/fc5855e8-46ce-11e7-9c39-26cdf340bf44.PNG)

**Comment by icc** [comment]
I'm wondering if this may be related to the theme. I just tested in Moodle3.3 with IE11 on Win7 and I'm not seeing any issue. Could you try opening the console(F12) and looking for any errors? 
It could, of course, be related to security settings in IE11. Are you using IE11 or are you using IE11 mode inside the Edge browser?

**Comment by Jarvil** [comment]
Hello,

This happens with Clean theme and I'm using proper Internet Explorer 11 on Windows 10. Tested with Edge also, it worked fine. Sometimes your windows version matters in IE problems so you should try this with Windows 10 also.

Everytime I click a card an error is added to the console, the screenshot is in finnish but it says roughly translated ;
````
"SCRIPT5007: Undefined or an empty reference property play cannot be retrieved 
e5633da0d0d74f21bca3140e598f073f84a12002.js (791,9)"
````
![error](https://cloud.githubusercontent.com/assets/15193418/26712500/cfc295b0-476f-11e7-8e37-f61a5cf22ebc.PNG)

**Comment by Jarvil** [comment]
Hello,

This seems to concern IE11 and Moodle 3.1.6 and mod_hvp 1.4 2017060600 & Memory Game (1.2.1) also you can turn all the pages in memory game at once. With chrome it works fine. Tested with clean theme. Errors are the same as with Moodle 3.3.

![memorygameie11](https://user-images.githubusercontent.com/15193418/27066622-16191af6-500e-11e7-8ed3-95ff4a33e253.PNG)

**Comment by icc** [comment]
I tried IE11 on Windows 10 through Browserstack without being able to reproduce it. If you add the following to your `config.php` temporarily we might be able to pinpoint the exact origin(file) that produces the error message:
```
$CFG->mod_hvp_aggregate_assets = 0;
```

Note that it must be inserted between these two lines:
```php
<?php  // Moodle configuration file

// ...

require_once(dirname(__FILE__) . '/lib/setup.php');
```

**Comment by Jarvil** [comment]
Hello,

It seems that with Moodle 3.1.6 (Build: 20170508) & H5P mod_hvp 1.2 (2017050300) & Memory Game (1.2.1) doesn't have this bug.

**Comment by Jarvil** [comment]
Hello,

This bug is still present in  mod_hvp | 1.42017060600, you can flip all the pages in memory game with IE11.

![error0](https://user-images.githubusercontent.com/15193418/28957157-652b4a42-78f9-11e7-9496-6ee63c4c361c.PNG)

![error1](https://user-images.githubusercontent.com/15193418/28957160-68e89806-78f9-11e7-8024-83d2c2eac36e.PNG)

![error2](https://user-images.githubusercontent.com/15193418/28957163-6b860e04-78f9-11e7-8034-cd07cfc0c7be.PNG)

**Comment by icc** [comment]
The bug is fixed and will be released shortly with the rest of the content types.
