### ISSUE TITLE
Responsiveness in Column - Have the pop-up fixed to center of screen?

### ISSUE THREAD

**Issue by niallmurphy-ie** [h5p/h5p-memory-game#26]
When used in a Column|iFrame, it seems that the pop-up goes to the top automatically and is not visible to users.

I wonder if the pop-up could be instead change to a fixed css position and also moved outside Column iFrame.

I can alter it myself but I'd have to change it on every update and think it would be a good feature for everyone.

**Comment by icc** [comment]
This issue has already been fixed but isn't released yet. Expect to see it in the next update.
